# ============================================================
# Pipeline configuration
# Add your paths & database configs
# ============================================================

[database]
host = localhost
port = 5432
dbname = iqvia_FHIR
user = fhir_dw
password = password

#In a real time env, The DB password details can be fetched from a secret vault

[source_files]
#Folder + file names where the upstream system drops the NDJSON files.
input_folder = data\input
patient_file = Patient.ndjson
allergy_file = AllergyIntolerance.ndjson

[pipeline]
create_tables_sql = sql\create_tables.sql
alert_folder = alerts  
