-- ============================================================
-- FHIR Allergy Star Schema Model (PostgreSQL)
--   * dim_patient  = SCD Type 2 (keeps history of changes)
--   * other dims   = SCD Type 1 (insert/update in place)
--   * fact table   = one row per allergy record
-- ============================================================

CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS dw;

-- ------------------------------------------------------------
-- STAGING (truncated and reloaded on every run by load_stage.py)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staging.stg_patient (
    patient_id     TEXT PRIMARY KEY,
    full_name      TEXT,
    gender         TEXT,
    birth_date     DATE,
    address_line   TEXT,
    city           TEXT,
    state          TEXT,
    postal_code    TEXT,
    country        TEXT,
    phone          TEXT,
    source_file    TEXT,
    source_line    INT
);


CREATE TABLE IF NOT EXISTS staging.stg_allergy (
    allergy_id       TEXT PRIMARY KEY,
    patient_id       TEXT,
    allergy_type     TEXT,
    category         TEXT,
    criticality      TEXT,
    allergen_system  TEXT,
    allergen_code    TEXT,
    allergen_display TEXT,
    reaction_code    TEXT,
    reaction_display TEXT,
    severity         TEXT,
    recorded_date    TIMESTAMP,
    source_file      TEXT,
    source_line      INT
);


-- Bad records (broken JSON, missing id, duplicates...) land here.
CREATE TABLE IF NOT EXISTS staging.rejects (
    reject_id    BIGSERIAL PRIMARY KEY,
    source_file  TEXT,
    source_line  INT,
    reason       TEXT,
    raw_line     TEXT,
    rejected_at  TIMESTAMP NOT NULL DEFAULT now()
);


-- ------------------------------------------------------------
-- DIMENSIONS: Loaded by load_dim.py
-- ------------------------------------------------------------
-- dim_patient is SCD Type 2:
--   * every change to a patient creates a NEW row (a new "version")
--   * the old row is closed: effective_to is filled, is_current = FALSE
--   * exactly one row per patient has is_current = TRUE


CREATE TABLE IF NOT EXISTS dw.dim_patient (
    patient_key    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id     TEXT NOT NULL,          -- natural key from source
    full_name      TEXT,
    gender         TEXT,
    birth_date     DATE,
    address_line   TEXT,
    city           TEXT,
    state          TEXT,
    postal_code    TEXT,
    country        TEXT,
    phone          TEXT,
    effective_from TIMESTAMP NOT NULL DEFAULT now(),
    effective_to   TIMESTAMP,            -- NULL = version still valid
    is_current     BOOLEAN NOT NULL DEFAULT TRUE
);

-- only 1 current version allowed per patient

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_patient_current
    ON dw.dim_patient (patient_id) WHERE is_current;

CREATE TABLE IF NOT EXISTS dw.dim_allergen (
    allergen_key     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allergen_code    TEXT NOT NULL,
    allergen_display TEXT,
    allergen_system  TEXT,
    category         TEXT NOT NULL,
    allergy_type     TEXT NOT NULL,
    UNIQUE (allergen_code, category, allergy_type)
);

CREATE TABLE IF NOT EXISTS dw.dim_reaction (
    reaction_key     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reaction_code    TEXT NOT NULL UNIQUE,
    reaction_display TEXT
);

CREATE TABLE IF NOT EXISTS dw.dim_severity (
    severity_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity     TEXT NOT NULL,
    criticality  TEXT NOT NULL,
    UNIQUE (severity, criticality)
);

-- ------------------------------------------------------------
-- FACT: one row per allergy record - Loaded by load_fact.py
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dw.fact_allergy_event (
    allergy_event_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_key       BIGINT NOT NULL REFERENCES dw.dim_patient(patient_key),
    allergen_key      BIGINT NOT NULL REFERENCES dw.dim_allergen(allergen_key),
    reaction_key      BIGINT NOT NULL REFERENCES dw.dim_reaction(reaction_key),
    severity_key      BIGINT NOT NULL REFERENCES dw.dim_severity(severity_key),
    recorded_date     TIMESTAMP,
    source_allergy_id TEXT NOT NULL UNIQUE,   -- natural key: safe re-runs
    source_file       TEXT,
    loaded_at         TIMESTAMP NOT NULL DEFAULT now()
);


CREATE INDEX IF NOT EXISTS ix_fact_patient  ON dw.fact_allergy_event (patient_key);
CREATE INDEX IF NOT EXISTS ix_fact_allergen ON dw.fact_allergy_event (allergen_key);

-- ------------------------------------------------------------
-- "Unknown" rows: facts with missing values point here instead of
-- holding NULL foreign keys. No record is lost because of a gap.
-- ------------------------------------------------------------

INSERT INTO dw.dim_patient (patient_id, full_name, gender, is_current)
SELECT 'UNKNOWN', 'Unknown Patient', 'unknown', TRUE
WHERE NOT EXISTS (SELECT 1 FROM dw.dim_patient WHERE patient_id = 'UNKNOWN');

INSERT INTO dw.dim_allergen (allergen_code, allergen_display, allergen_system, category, allergy_type)
VALUES ('UNKNOWN', 'Unknown Allergen', 'unknown', 'unknown', 'unknown')
ON CONFLICT (allergen_code, category, allergy_type) DO NOTHING;

INSERT INTO dw.dim_reaction (reaction_code, reaction_display)
VALUES ('UNKNOWN', 'Unknown Reaction')
ON CONFLICT (reaction_code) DO NOTHING;

INSERT INTO dw.dim_severity (severity, criticality)
VALUES ('unknown', 'unknown')
ON CONFLICT (severity, criticality) DO NOTHING;
